### ISSUE TITLE
Layout solution tab

### ISSUE THREAD

**Issue by zinzireimert** [TNOCS/MultiCriteriaAnalysis#38] opened 2015-05-03 19:45 UTC
‘Solution’ tab should remove the scenario list (left side currently).

**Comment by erikvullings** [comment] 2015-05-15 09:13
So we only show the criteria, and use a dropdown to select the scenario.
Issue #33.

**Comment by erikvullings** [comment] 2015-05-15 09:14
Duplicate of issue #33.

**Closed** 2015-05-15 09:14 UTC
